student_count = 9

# list of students
puts "Students in my cohort at MakersAcademy"
puts "--------------------------------------"
puts "Mario Gintili"
puts "Mikhail Dubov"
puts "Karolis Noreika"
puts "Michael Sidon"
puts "Charles De Barros"
puts "Ruslan Vikhor"
puts "Toby Retallick"
puts "Mark Mekhaiel"
puts "Sarah Young"
puts "Hannah Wight"
puts "Khushkaran Singh"
puts "Rick brunstedt"
puts "Manjit Singh"
puts "Alex Gaudiosi"
puts "Ross Hepburn"
puts "Natascia Marchese"
puts "Tiffanie Chia"
puts "Matthew Thomas"
puts "Freddy McGroarty"
puts "Tyler Rollins"
puts "Richard Curteis"
puts "Anna Yanova"
puts "Andrew Cumine" 
print "\n"

# total students count
puts "Overall, we have #{student_count} great students"
