student_count = 23

puts "List of all the awesome students at MA"
puts "--------------------------------------"
puts "Mario Gintili"
puts "Mikhail Dubov"
puts "Karolis Noreika"
puts "Michael Sidon"
puts "Charles De Barros"
puts "Ruslan Vikhor"
puts "Toby Retallick"
puts "Mark Mekhaiel"
puts "Sarah Young"
puts "Hannah Wight"
puts "Khushkaran Singh"
puts "Rick brunstedt"
puts "Manjit Singh"
puts "Alex Gaudiosi"
puts "Ross Hepburn"
puts "Natascia Marchese"
puts "Tiffanie Chia"
puts "Matthew Thomas"
puts "Freddy McGroarty"
puts "Tyler Rollins"
puts "Richard Curteis"
puts "Anna Yanova"
puts "Andrew Cumine" 


puts "Overall, we have #{student_count} great students!"